pub mod modules;
pub mod templates;

use crate::ir::SrcGenIR;
use crate::{GeneratedRust, SrcGenBackend};
use proc_macro2::TokenStream;

pub fn generate_modules(ir: &SrcGenIR, backend: SrcGenBackend) -> Result<GeneratedRust, String> {
    let files = modules::generate_module_files(ir, backend)?;
    let root = build_root_module();
    Ok(GeneratedRust { root, files })
}

fn build_root_module() -> String {
    [
        "// Code generated by shacl-srcgen-compiler. DO NOT EDIT.",
        "#![allow(unused_variables)]",
        "#![allow(dead_code)]",
        "#![allow(unused_mut)]",
        "#![allow(unused_imports)]",
        "#![allow(unused_comparisons)]",
        "include!(\"prelude.rs\");",
        "include!(\"paths.rs\");",
        "include!(\"targets.rs\");",
        "include!(\"validators_property.rs\");",
        "include!(\"validators_node.rs\");",
        "include!(\"inference.rs\");",
        "include!(\"report.rs\");",
        "include!(\"run.rs\");",
        "",
    ]
    .join("\n")
}

pub(crate) fn render_tokens_as_module(tokens: TokenStream) -> Result<String, String> {
    let syntax = syn::parse_file(&tokens.to_string())
        .map_err(|err| format!("failed to parse generated tokens: {err}"))?;
    Ok(prettyplease::unparse(&syntax))
}
