"""Type declarations for the native :mod:`shifty._shifty` extension."""

from typing import Any, ClassVar, Dict, List, Optional, Tuple, Union

__version__: str


class ConstraintKind:
    Unknown: ClassVar[ConstraintKind]
    Top: ClassVar[ConstraintKind]
    Constant: ClassVar[ConstraintKind]
    ClassMembership: ClassVar[ConstraintKind]
    ValueType: ClassVar[ConstraintKind]
    NodeKind: ClassVar[ConstraintKind]
    Closed: ClassVar[ConstraintKind]
    Equals: ClassVar[ConstraintKind]
    Disjoint: ClassVar[ConstraintKind]
    LessThan: ClassVar[ConstraintKind]
    LessThanOrEquals: ClassVar[ConstraintKind]
    UniqueLang: ClassVar[ConstraintKind]
    Negation: ClassVar[ConstraintKind]
    Conjunction: ClassVar[ConstraintKind]
    Disjunction: ClassVar[ConstraintKind]
    Cardinality: ClassVar[ConstraintKind]
    Sparql: ClassVar[ConstraintKind]
    Expression: ClassVar[ConstraintKind]
    def __str__(self) -> str: ...


class SparqlDiagnostic:
    @property
    def query(self) -> str: ...
    @property
    def bindings(self) -> List[Tuple[str, str]]: ...
    @property
    def results(self) -> List[List[Tuple[str, str]]]: ...
    @property
    def fallback_reason(self) -> Optional[str]: ...


class Constraint:
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> ConstraintKind: ...
    @property
    def render(self) -> str: ...
    @property
    def definition(self) -> str: ...
    @property
    def json(self) -> str: ...
    def __str__(self) -> str: ...


class Reason:
    @property
    def value(self) -> str: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def message(self) -> str: ...
    @property
    def author_message(self) -> Optional[str]: ...
    @property
    def severity(self) -> str: ...
    @property
    def constraint(self) -> Constraint: ...
    @property
    def constraint_kind(self) -> ConstraintKind: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def statement_id(self) -> int: ...
    @property
    def sparql_diagnostic(self) -> Optional[SparqlDiagnostic]: ...


class Violation:
    @property
    def focus_node(self) -> str: ...
    @property
    def statement_id(self) -> int: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def shape_name(self) -> Optional[str]: ...
    @property
    def severity(self) -> str: ...
    @property
    def reasons(self) -> List[Reason]: ...


class AlgebraResult:
    @property
    def conforms(self) -> bool: ...
    @property
    def violations(self) -> List[Violation]: ...
    @property
    def results_text(self) -> str: ...
    def __bool__(self) -> bool: ...


class W3cResult:
    @property
    def conforms(self) -> bool: ...
    @property
    def report_turtle(self) -> str: ...
    @property
    def results_text(self) -> str: ...
    def __bool__(self) -> bool: ...


class PropertyWitness:
    @property
    def focus(self) -> str: ...
    @property
    def shape(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def values(self) -> List[str]: ...


class InferResult:
    @property
    def inferred_count(self) -> int: ...
    @property
    def diagnostics(self) -> List[str]: ...
    @property
    def graph_ntriples(self) -> str: ...


class PreparedValidator:
    def __init__(
        self,
        shapes: Optional[bytes] = ...,
        shapes_path: Optional[str] = ...,
        shapes_format: str = ...,
        base: Optional[str] = ...,
    ) -> None: ...
    @property
    def diagnostics(self) -> List[str]: ...
    def validate_algebra(
        self,
        data: Optional[bytes] = ...,
        data_path: Optional[str] = ...,
        data_format: str = ...,
        graph_mode: str = ...,
        entry_shape_names: Optional[List[str]] = ...,
        run_infer: bool = ...,
        minimum_severity: str = ...,
        sort_results: bool = ...,
        on_unsupported: str = ...,
    ) -> AlgebraResult: ...
    def validate_w3c(
        self,
        data: Optional[bytes] = ...,
        data_path: Optional[str] = ...,
        data_format: str = ...,
        graph_mode: str = ...,
        entry_shape_names: Optional[List[str]] = ...,
        run_infer: bool = ...,
        minimum_severity: str = ...,
        sort_results: bool = ...,
        on_unsupported: str = ...,
    ) -> W3cResult: ...
    def witnesses(
        self,
        data: Optional[bytes] = ...,
        data_path: Optional[str] = ...,
        data_format: str = ...,
        key_path: Optional[str] = ...,
        graph_mode: str = ...,
        run_infer: bool = ...,
        on_unsupported: str = ...,
    ) -> List[PropertyWitness]: ...


class EvidenceKind:
    Irrefutable: ClassVar[EvidenceKind]
    AtomHeld: ClassVar[EvidenceKind]
    AllHeld: ClassVar[EvidenceKind]
    AnyHeld: ClassVar[EvidenceKind]
    CountHeld: ClassVar[EvidenceKind]
    AllValuesHeld: ClassVar[EvidenceKind]
    NotHeld: ClassVar[EvidenceKind]
    Blocked: ClassVar[EvidenceKind]
    Coinductive: ClassVar[EvidenceKind]
    AtomFailed: ClassVar[EvidenceKind]
    RelationalFailed: ClassVar[EvidenceKind]
    ClosedFailed: ClassVar[EvidenceKind]
    NotFailed: ClassVar[EvidenceKind]
    AllFailed: ClassVar[EvidenceKind]
    AnyFailed: ClassVar[EvidenceKind]
    CountLow: ClassVar[EvidenceKind]
    CountHigh: ClassVar[EvidenceKind]
    Opaque: ClassVar[EvidenceKind]
    @property
    def status(self) -> str: ...
    def __str__(self) -> str: ...


class WitnessKind:
    Atom: ClassVar[WitnessKind]
    Relational: ClassVar[WitnessKind]
    Closed: ClassVar[WitnessKind]
    CountLow: ClassVar[WitnessKind]
    CountHigh: ClassVar[WitnessKind]
    Not: ClassVar[WitnessKind]
    Opaque: ClassVar[WitnessKind]


class WitnessAtom:
    @property
    def kind(self) -> WitnessKind: ...
    @property
    def evidence_kind(self) -> EvidenceKind: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def constraint_kind(self) -> ConstraintKind: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def detail(self) -> str: ...


class SatKind:
    Atom: ClassVar[SatKind]
    Match: ClassVar[SatKind]
    Not: ClassVar[SatKind]
    Blocked: ClassVar[SatKind]
    Coinductive: ClassVar[SatKind]


class SatAtom:
    @property
    def kind(self) -> SatKind: ...
    @property
    def evidence_kind(self) -> EvidenceKind: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def detail(self) -> str: ...


class TargetKind:
    Class: ClassVar[TargetKind]
    SubjectsOf: ClassVar[TargetKind]
    ObjectsOf: ClassVar[TargetKind]
    Node: ClassVar[TargetKind]
    Path: ClassVar[TargetKind]
    Sparql: ClassVar[TargetKind]


class Target:
    @property
    def kind(self) -> TargetKind: ...
    @property
    def value(self) -> Optional[str]: ...
    @property
    def path(self) -> Optional[str]: ...
    @property
    def render(self) -> str: ...
    def __str__(self) -> str: ...


class EvidenceNode:
    @property
    def evidence_kind(self) -> EvidenceKind: ...
    @property
    def kind(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def json(self) -> str: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...


class PathSupport:
    @property
    def kind(self) -> str: ...
    @property
    def triple(self) -> Optional[str]: ...
    @property
    def children(self) -> List[PathSupport]: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...


class MissingObligation:
    @property
    def constraint_id(self) -> int: ...
    @property
    def node(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def observed_count(self) -> int: ...
    @property
    def required_count(self) -> int: ...
    @property
    def missing(self) -> int: ...
    @property
    def qualifier(self) -> Constraint: ...


class Failure:
    @property
    def focus(self) -> str: ...
    @property
    def statement(self) -> int: ...
    @property
    def statement_id(self) -> int: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def constraint_kind(self) -> ConstraintKind: ...
    @property
    def constraint(self) -> Constraint: ...
    @property
    def target(self) -> str: ...
    @property
    def shape_name(self) -> Optional[str]: ...
    @property
    def selector(self) -> Target: ...
    @property
    def shape_iri(self) -> Optional[str]: ...
    def summary(self) -> List[WitnessAtom]: ...
    def explain(self) -> str: ...
    def walk(self) -> List[EvidenceNode]: ...
    def supporting_triples(self) -> List[str]: ...
    def path_supports(self) -> List[PathSupport]: ...
    def matched_values(self) -> List[str]: ...
    def values_for_path(self, path: str) -> List[str]: ...
    def missing_obligations(self) -> List[MissingObligation]: ...
    def offending_values(self) -> List[str]: ...
    def source_constraints(self) -> List[int]: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def repair_tree(self) -> RepairTree: ...


class Satisfaction:
    @property
    def focus(self) -> str: ...
    @property
    def statement(self) -> int: ...
    @property
    def statement_id(self) -> int: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def constraint_kind(self) -> ConstraintKind: ...
    @property
    def constraint(self) -> Constraint: ...
    @property
    def target(self) -> str: ...
    @property
    def shape_name(self) -> Optional[str]: ...
    @property
    def selector(self) -> Target: ...
    @property
    def shape_iri(self) -> Optional[str]: ...
    def summary(self) -> List[SatAtom]: ...
    def explain(self) -> str: ...
    def walk(self) -> List[EvidenceNode]: ...
    def supporting_triples(self) -> List[str]: ...
    def path_supports(self) -> List[PathSupport]: ...
    def matched_values(self) -> List[str]: ...
    def values_for_path(self, path: str) -> List[str]: ...
    def missing_obligations(self) -> List[MissingObligation]: ...
    def offending_values(self) -> List[str]: ...
    def source_constraints(self) -> List[int]: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...


class FocusEvaluation:
    @property
    def focus(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def satisfaction(self) -> Optional[Satisfaction]: ...
    @property
    def failure(self) -> Optional[Failure]: ...
    @property
    def evidence(self) -> Union[Satisfaction, Failure]: ...
    @property
    def progress(self) -> Optional[EvaluationProgress]: ...


class ChildEvaluation:
    @property
    def source_constraint_ref(self) -> int: ...
    @property
    def normalized_constraint_ref(self) -> Optional[int]: ...
    @property
    def status(self) -> str: ...
    @property
    def constraint_kind(self) -> ConstraintKind: ...


class EvaluationProgress:
    @property
    def evaluated_children(self) -> List[ChildEvaluation]: ...


class StatementEvaluation:
    @property
    def source_statement_id(self) -> int: ...
    @property
    def normalized_statement_id(self) -> Optional[int]: ...
    @property
    def source_constraint_id(self) -> int: ...
    @property
    def normalized_constraint_id(self) -> Optional[int]: ...
    @property
    def constraint_kind(self) -> ConstraintKind: ...
    @property
    def constraint(self) -> Constraint: ...
    @property
    def target(self) -> str: ...
    @property
    def shape_name(self) -> Optional[str]: ...
    @property
    def selector(self) -> Target: ...
    @property
    def shape_iri(self) -> Optional[str]: ...
    @property
    def selected_foci(self) -> List[FocusEvaluation]: ...


class ConformanceRun:
    @property
    def conforms(self) -> bool: ...
    @property
    def selected_pairs(self) -> int: ...
    @property
    def passed(self) -> int: ...
    @property
    def failed(self) -> int: ...
    def __bool__(self) -> bool: ...


class SelectedPair:
    @property
    def focus(self) -> str: ...
    @property
    def normalized_statement(self) -> int: ...
    @property
    def source_statements(self) -> List[int]: ...


class EvidenceRun:
    @property
    def conforms(self) -> bool: ...
    @property
    def statements(self) -> List[StatementEvaluation]: ...
    def results_for(self, focus: str) -> List[FocusEvaluation]: ...
    def failures_for(self, focus: str) -> List[Failure]: ...
    def satisfactions_for(self, focus: str) -> List[Satisfaction]: ...
    def failure_for(self, focus: str, statement: Optional[int] = ...) -> Failure: ...
    def covered_shapes(self) -> List[str]: ...
    def results_for_shape(self, shape_iri: str) -> List[FocusEvaluation]: ...
    def failures_for_shape(self, shape_iri: str) -> List[Failure]: ...
    def satisfactions_for_shape(self, shape_iri: str) -> List[Satisfaction]: ...
    def satisfaction_for(
        self, focus: str, statement: Optional[int] = ...
    ) -> Satisfaction: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_compact_json(self, include_catalog: bool = ...) -> str: ...
    def to_compact_dict(self, include_catalog: bool = ...) -> Dict[str, Any]: ...
    def __bool__(self) -> bool: ...


class EvidenceSession:
    def __init__(
        self,
        shapes: Optional[bytes] = ...,
        shapes_path: Optional[str] = ...,
        shapes_format: str = ...,
        data: Optional[bytes] = ...,
        data_path: Optional[str] = ...,
        data_format: str = ...,
        run_infer: bool = ...,
        graph_mode: str = ...,
        base: Optional[str] = ...,
    ) -> None: ...
    @property
    def diagnostics(self) -> List[str]: ...
    def validate(
        self,
        entry_shape_names: Optional[List[str]] = ...,
        minimum_severity: str = ...,
        sort_results: bool = ...,
    ) -> EvidenceRun: ...
    def revalidate(
        self,
        delta: RepairDelta,
        infer: Optional[bool] = ...,
        entry_shape_names: Optional[List[str]] = ...,
        minimum_severity: str = ...,
        sort_results: bool = ...,
    ) -> EvidenceRun: ...
    def validate_conformance(
        self, entry_shape_names: Optional[List[str]] = ...
    ) -> ConformanceRun: ...
    def find_failures(
        self, entry_shape_names: Optional[List[str]] = ...
    ) -> Tuple[ConformanceRun, List[SelectedPair]]: ...
    def explain(self, pair: SelectedPair) -> EvidenceRun: ...
    def explain_canonical(self, pair: SelectedPair) -> EvidenceRun: ...
    def constraints(self) -> Dict[str, Any]: ...


class RepairSession:
    def __init__(
        self,
        shapes: Optional[bytes] = ...,
        shapes_path: Optional[str] = ...,
        shapes_format: str = ...,
        data: Optional[bytes] = ...,
        data_path: Optional[str] = ...,
        data_format: str = ...,
        run_infer: bool = ...,
        base: Optional[str] = ...,
    ) -> None: ...
    @property
    def diagnostics(self) -> List[str]: ...
    def witnesses(self) -> List[Failure]: ...
    def witnesses_for(self, shape_iri: str) -> List[Failure]: ...
    def satisfactions_for(self, shape_iri: str) -> List[Satisfaction]: ...
    def gate(self, delta: RepairDelta) -> RepairOutcome: ...
    def current_ntriples(self) -> str: ...
    def apply_ntriples(self, delta: RepairDelta) -> str: ...
    def repair_node_against(self, node: str, shape_id: int) -> Optional[RepairTree]: ...
    def describe_shape(self, shape_id: int) -> str: ...
    def advance(self, delta: RepairDelta) -> RepairSession: ...


class RepairOrigin:
    @property
    def statement_id(self) -> Optional[int]: ...
    @property
    def path(self) -> List[int]: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def node(self) -> Optional[str]: ...
    @property
    def status(self) -> str: ...
    @property
    def evidence_kind(self) -> EvidenceKind: ...
    @property
    def kind(self) -> str: ...


class RepairTree:
    @property
    def root_id(self) -> int: ...
    @property
    def is_blocked(self) -> bool: ...
    def origins(self, node_id: Optional[int] = ...) -> List[RepairOrigin]: ...
    def explain(self) -> str: ...
    def holes(self) -> List[Hole]: ...
    def choices(self) -> List[Choice]: ...
    def instantiate(self, plan: RepairPlan) -> Instantiated: ...


class Hole:
    @property
    def id(self) -> int: ...
    @property
    def constraint(self) -> str: ...
    def candidates(self, limit: int = ...) -> List[str]: ...
    @property
    def conforms_to(self) -> Optional[int]: ...
    @property
    def conforms_to_shapes(self) -> List[int]: ...
    def sub_shapes(self) -> List[Tuple[int, str]]: ...


class ChoiceKind:
    Any: ClassVar[ChoiceKind]
    Repeat: ClassVar[ChoiceKind]


class Choice:
    @property
    def node_id(self) -> int: ...
    @property
    def kind(self) -> ChoiceKind: ...
    @property
    def branches(self) -> Optional[int]: ...
    @property
    def min(self) -> Optional[int]: ...
    @property
    def max(self) -> Optional[int]: ...


class RepairPlan:
    def __init__(self) -> None: ...
    def choose(self, node_id: int, branch_index: int) -> None: ...
    def count(self, node_id: int, n: int) -> None: ...
    def bind(self, hole_id: int, value: str) -> None: ...
    def clear(self, id: int) -> None: ...


class Instantiated:
    @property
    def delta(self) -> RepairDelta: ...
    @property
    def open_holes(self) -> List[Hole]: ...
    @property
    def open_choices(self) -> List[int]: ...
    @property
    def is_complete(self) -> bool: ...


class RepairDelta:
    @staticmethod
    def from_ntriples(add: str = ..., delete: str = ...) -> RepairDelta: ...
    @property
    def add(self) -> List[Tuple[str, str, str]]: ...
    @property
    def delete(self) -> List[Tuple[str, str, str]]: ...
    @property
    def is_empty(self) -> bool: ...


class RepairOutcome:
    @property
    def is_sound(self) -> bool: ...
    @property
    def is_progress(self) -> bool: ...
    @property
    def fixed(self) -> List[Violation]: ...
    @property
    def introduced(self) -> List[Violation]: ...
    @property
    def remaining(self) -> List[Violation]: ...


def version() -> str: ...
def _validate_algebra(
    data: Optional[bytes] = ...,
    data_path: Optional[str] = ...,
    data_format: str = ...,
    shapes: Optional[bytes] = ...,
    shapes_path: Optional[str] = ...,
    shapes_format: str = ...,
    graph_mode: str = ...,
    entry_shape_names: Optional[List[str]] = ...,
    run_infer: bool = ...,
    minimum_severity: str = ...,
    sort_results: bool = ...,
    on_unsupported: str = ...,
    base: Optional[str] = ...,
) -> AlgebraResult: ...
def _validate_w3c(
    data: Optional[bytes] = ...,
    data_path: Optional[str] = ...,
    data_format: str = ...,
    shapes: Optional[bytes] = ...,
    shapes_path: Optional[str] = ...,
    shapes_format: str = ...,
    graph_mode: str = ...,
    entry_shape_names: Optional[List[str]] = ...,
    run_infer: bool = ...,
    minimum_severity: str = ...,
    sort_results: bool = ...,
    on_unsupported: str = ...,
    base: Optional[str] = ...,
) -> W3cResult: ...
def _infer(
    data: Optional[bytes] = ...,
    data_path: Optional[str] = ...,
    data_format: str = ...,
    shapes: Optional[bytes] = ...,
    shapes_path: Optional[str] = ...,
    shapes_format: str = ...,
    on_unsupported: str = ...,
    base: Optional[str] = ...,
) -> InferResult: ...
def expand_evidence_json(compact: str, catalog: Optional[str] = ...) -> str: ...
